name: build-jammy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Free disk space on runner
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /opt/hostedtoolcache || true
          sudo docker system prune -af || true
          sudo apt-get clean
          sudo rm -rf ~/.cache
          df -h
      - name: Build
        run: |
          cd scripts
          sed -i -E -e 's/^TARGET_UBUNTU_VERSION=.*/TARGET_UBUNTU_VERSION="jammy"/' -e 's/^TARGET_ROS_VERSION=.*/TARGET_ROS_VERSION="humble"/' config.sh
          ./build.sh -
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UbuntuRAI
          path: |
            scripts/UbuntuRAI.iso
            scripts/image/md5sum.txt
